[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
randomness = "3pfz13JhzVwtWcZ9WRuQ4o5QjPAbzv9oF7fTsvi26Ptw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
